Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2023-10, with the labels that each got.

#1552 #1167 persistent filters for projects table
  src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
Labels: Approved

#1561 #1532 added seed data to orioles
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Approved

#1570 #976 added 8 members to team ravens
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Ready for Review

#1540 #965 Added team name to project page
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
Labels: Approved, Sean

#1590 #1479 added bom to schema
  src/backend/src/prisma/migrations/20231005145708_add_bom/migration.sql
  src/backend/src/prisma/schema.prisma
Labels: Ready for Review, Reid

#1567 #1330: redesigned the create wp endpoint
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/prisma/seed-data/work-packages.seed.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/tests/test-data/wbs-element.test-data.ts
  src/backend/tests/work-packages.test.ts
Labels: Ready for Review, Ji-min

#1579 #1168: Added persistent filters for CR table
  src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
Labels: Reviewed

#1563 #954: fixed bug with stage when editing workpackage
  src/backend/src/services/work-packages.services.ts
  src/backend/src/utils/changes.utils.ts
Labels: Reviewed

#1620 #1507 ha nguyen wbs element search
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
Labels: Approved, Ji-min

#1601 #1597 right align pencil icon
  src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
Labels: Ready for Review, Reid

#1636 #1631 bradford derby credits
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: credits

#1624 #1324 Changed ReactHookEditableList and associated forms
  src/frontend/src/components/ReactHookEditableList.tsx
  src/frontend/src/pages/CreateWorkPackagePage/CreateWorkPackageFormView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
Labels: Reviewed, Reid

#1571 #1328-work package redesign, activities and deliverables
  src/frontend/src/components/ReactHookEditableList.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
Labels: Ready for Review, Reid

#1630 #1498: removed use of any from BlockedBy.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/BlockedBy.tsx
  src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/BlockedBy.tsx
Labels: Reviewed, Reid

#1617 #1516 fixed team member display
  src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
Labels: Reviewed, Ji-min

#1462 #1320 Create project endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/seed-data/projects.seed.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/utils/projects.utils.ts
  src/backend/tests/projects.test.ts
Labels: Ready for Review, Reid

#1575 #1189: Changed Work Package Stage Integration to Install
  src/backend/src/prisma/migrations/20231010194436_integration_to_install/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/utils/validation.utils.ts
  src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
  src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.test.tsx
  src/frontend/src/tests/test-support/test-data/work-packages.stub.ts
  src/frontend/src/utils/enum-pipes.ts
  src/shared/src/types/work-package-types.ts
Labels: Ready for Review, Reid

#1616 #1307 : Changed dateReviewed to dateImplemented
  src/backend/src/transformers/change-requests.transformer.ts
  src/backend/src/utils/change-requests.utils.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/work-packages.test.ts
  src/frontend/src/components/ChangeRequestDropdown.tsx
Labels: Ready for Review, Sean

#1654 #1614-change-datedelivered-to-itemdelivered
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
Labels: Reviewed, Reid

#1313 #1290 - add allowed refund sources to expense type
  src/backend/src/controllers/reimbursement-requests.controllers.ts
  src/backend/src/prisma/migrations/20230829222742_add_allowed_refund_sources/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/transformers/reimbursement-requests.transformer.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
  src/frontend/src/hooks/finance.hooks.ts
  src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodeFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodesTable.tsx
  src/frontend/src/pages/FinancePage/CreateReimbursementRequest.tsx
  src/frontend/src/pages/FinancePage/EditReimbursementRequest/EditReimbursementRequest.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Reviewed

#1656 #1521 BOM create manufacturer endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Reviewed, Reid

#1634 #1554 form validation fix for crID for project/wp edit
  src/frontend/src/components/ChangeRequestDropdown.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
Labels: Ready for Review, Reid

#1646 #1522: added create material type endpoint with tests
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Ready for Review, Ji-min

#1648 #1458: All Projects Table filtered by ACTIVE
  src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
Labels: Approved, Ryan

#1664 #1657 Allowed product cost to be less than 1
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Labels: Ready for Review, Reid

#1629 #1533 create new team with 12 members
  src/backend/src/prisma/seed-data/teams.seed.ts
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Reviewed, Reid

#1671 #1580: added "Date Submitted to sabo" to reimbursement section
  src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
Labels: Reviewed, Reid

#1665 #1584 changed 'total owed' to 'currently owed' and fixed owed amount …
  src/frontend/src/pages/FinancePage/RefundsSection.tsx
Labels: Ready for Review, Reid

#1669 #1666 Added error message for cost and description of products on finance form
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Labels: Ready for Review, Reid

#1663 #1509 create assembly endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/migrations/20231024124220_add_bom/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/utils/teams.utils.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Reviewed, Reid

#1559 #745 used projectManagerID and projectLeadId to store numbers
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/work-packages.services.ts
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
Labels: Ready for Review, Reid
