Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2023-11, with the labels that each got.

#1678 #1322 redesigned project details section and created teams dropdown
  src/frontend/src/components/ChangeRequestDropdown.tsx
  src/frontend/src/components/NERAutocomplete.tsx
  src/frontend/src/components/TeamsDropdown.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditDetails.tsx
Labels: Reviewed, Reid

#1673 #1297 : Implementing first overflow option
  src/frontend/src/components/VerticalDetailDisplay.tsx
Labels: Approved, Sean

#1553 #1489 remove any keyword from finance.hooks.ts
  src/frontend/src/hooks/finance.hooks.ts
Labels: Reviewed, Reid

#1628 #1534 Created a new team in the Seed Data
  src/backend/src/prisma/seed-data/teams.seed.ts
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Reviewed, Reid

#1651 #1525 Create Materials Endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/src/utils/validation.utils.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
  src/shared/src/types/project-types.ts
Labels: Ready for Review, Reid

#1619 #1096 work package leads can create tasks
  src/backend/src/services/tasks.services.ts
  src/backend/tests/tasks.test.ts
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx
Labels: Ready for Review, Reid

#1667 #1529: Added more data to seed.ts and initialized them on users.seeds.ts
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Ready for Review, Reid

#1693 Fixes Issue #1512: Members of a team should be able to create tasks
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx
Labels: Ready for Review, Reid

#1689 #1504 replaced any type with Task type
  src/backend/tests/tasks.test.ts
Labels: Approved, Sean

#1685 #1576 Threw an exception when there is an existing phone number in th…
  src/backend/src/services/users.services.ts
  src/backend/tests/users.test.ts
Labels: Approved, Sean

#1686 #1610 Added deny reimbursement request endpoint
  src/backend/src/controllers/reimbursement-requests.controllers.ts
  src/backend/src/prisma/migrations/20231109224241_deny_rr/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
  src/frontend/src/utils/reimbursement-request.utils.ts
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Reviewed, Reid

#1548 #1417 - get many work packages endpoint
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/src/transformers/work-packages.transformer.ts
  src/backend/tests/work-packages.test.ts
Labels: Ready for Review, Ryan

#1702 #1623 - work package showing wrong blockedBy bug
  src/backend/src/routes/work-packages.routes.ts
  src/frontend/src/apis/work-packages.api.ts
  src/frontend/src/hooks/work-packages.hooks.ts
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/WorkPackageSummary.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.tsx
  src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
  src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackagePage.test.tsx
  src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageViewContainer.test.tsx
  src/frontend/src/tests/test-support/mock-hooks.ts
  src/frontend/src/utils/urls.ts
Labels: Ready for Review

#1675 #1519 get all manufacturers endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma-query-args/manufacturers.query-args.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/manufacturer.transformer.ts
  src/backend/tests/projects.test.ts
  src/shared/src/types/project-types.ts
Labels: Reviewed, Reid

#1690 #1323: removed page block
  src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
Labels: front-end, Reviewed, Reid

#1672 #1658 Allowed finance team to edit all RR's
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/utils/reimbursement-requests.utils.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
Labels: Reviewed, Reid

#1695 #1660 no expansion with too many products
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Labels: Ready for Review, Sean

#1676 #1641 other CRs from user popup
  src/frontend/src/components/ChangeRequestDetailCard.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
Labels: Ready for Review, Reid

#1701 #1526 edit material endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/migrations/20231119042617_add_bom/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/src/utils/projects.utils.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Ready for Review, Reid

#1684 1524 Created the delete materials type endpoint and tested it
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/migrations/20231119054311_add_bom/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Ready for Review, Reid

#1697 #1523 : Delete manufacturer endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/migrations/20231119081759_add_bom/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/manufacturer.transformer.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Reviewed, Sean

#1564 #1425 - Allow Finance Leads to Edit Vendors on the Admin Page
  .github/workflows/run-tests.yml
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/transformers/auth-user.transformer.ts
  src/backend/src/utils/reimbursement-requests.utils.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/backend/tests/test-data/users.test-data.ts
  src/frontend/src/layouts/NavTopBar/NavUserMenu.tsx
  src/frontend/src/pages/AdminToolsPage/AdminTools.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx
  src/frontend/src/utils/users.ts
  src/shared/src/types/user-types.ts
Labels: Reviewed, Ji-min

#1677 #1528 Create assign material assembly route and controller
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Ready for Review, Reviewed, Reid

#1712 #1520: added get all material types endpoint with the tests
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma-query-args/material-type.query-args.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/manufacturer.transformer.ts
  src/backend/src/transformers/material-type.transformer.ts
  src/backend/tests/projects.test.ts
  src/shared/src/types/project-types.ts
Labels: Reviewed, Reid

#1700 Issue #1527 initial push
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/tests/projects.test.ts
Labels: back-end, medium

#1698 #1593-Made a check for old reviewers before pinging
  src/backend/src/services/change-requests.services.ts
  src/backend/tests/change-requests.test.ts
Labels: Reviewed, Reid

#1704 #1325 refactor editprojectcontainer
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/frontend/src/components/Link/LinksEditView.tsx
  src/frontend/src/components/PageLayout.tsx
  src/frontend/src/layouts/PageTitle/PageTitle.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectEdit/ProjectEditContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectCreateContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectFormDetails.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectPage.tsx
  src/frontend/src/pages/ProjectsPage/Projects.tsx
  src/frontend/src/utils/form.ts
  src/frontend/src/utils/types.ts
Labels: Reviewed, Reid

#1674 #1535 - Add Other Reasons to Reimbursement Products
  src/backend/src/controllers/reimbursement-requests.controllers.ts
  src/backend/src/prisma-query-args/reimbursement-products.query-args.ts
  src/backend/src/prisma-query-args/reimbursement-requests.query-args.ts
  src/backend/src/prisma/migrations/20231112060254_other_option_product_rr/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/transformers/reimbursement-requests.transformer.ts
  src/backend/src/utils/reimbursement-requests.utils.ts
  src/backend/src/utils/validation.utils.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
  src/frontend/src/hooks/finance.hooks.ts
  src/frontend/src/pages/FinancePage/EditReimbursementRequest/EditReimbursementRequestRenderedDefaultValues.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementProductsView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
  src/frontend/src/utils/users.ts
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Ready for Review

#1714 #1713 Bill of Materials Frontend
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma-query-args/bom.query-args.ts
  src/backend/src/prisma-query-args/manufacturers.query-args.ts
  src/backend/src/prisma-query-args/material-type.query-args.ts
  src/backend/src/prisma-query-args/projects.query-args.ts
  src/backend/src/prisma/migrations/20231122182628_add_boms/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/manufacturer.transformer.ts
  src/backend/src/transformers/material-type.transformer.ts
  src/backend/src/transformers/material.transformer.ts
  src/backend/src/transformers/projects.transformer.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
  src/backend/tests/test-data/work-packages.test-data.ts
  src/frontend/src/apis/bom.api.ts
  src/frontend/src/apis/transformers/bom.transformers.ts
  src/frontend/src/components/NERAutocomplete.tsx
  src/frontend/src/components/NERModal.tsx
  src/frontend/src/components/ReactHookTextField.tsx
  src/frontend/src/hooks/bom.hooks.ts
  src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/CreateManufacturerFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/CreateMaterialTypeFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/ManufacturerTable.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/MaterialTypeTable.tsx
  src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequest.tsx
  src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/AssemblyForm/AssemblyForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/AssemblyForm/AssemblyFormView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/AssemblyForm/CreateAssemblyModal.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableWrapper.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/CreateMaterialModal.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/EditMaterialModal.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOMTab.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
  src/frontend/src/tests/test-support/test-data/projects.stub.ts
  src/frontend/src/tests/test-support/test-data/work-packages.stub.ts
  src/frontend/src/utils/bom.utils.ts
  src/frontend/src/utils/tables.ts
  src/frontend/src/utils/urls.ts
  src/shared/index.ts
  src/shared/src/types/bom-types.ts
  src/shared/src/types/project-types.ts
Labels: Ready for Review

#1716 #1577 receipt display update
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
Labels: Ready for Review, Ji-min

#1707 #1329 WP Form Refactor
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/routes/work-packages.routes.ts
  src/frontend/src/components/ChangeRequestDropdown.tsx
  src/frontend/src/components/PageLayout.tsx
  src/frontend/src/hooks/work-packages.hooks.ts
  src/frontend/src/layouts/PageTitle/PageTitle.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
  src/frontend/src/pages/ProjectsPage/Projects.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/EditModeOptions.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageEditContainer/WorkPackageEditContainer.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackagePage.tsx
  src/frontend/src/pages/WorkPackageForm/CreateWorkPackageForm.tsx
  src/frontend/src/pages/WorkPackageForm/EditWorkPackageForm.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormDetails.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
  src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageEditContainer/EditModeOptions.test.tsx
  src/frontend/src/tests/test-support/test-data/change-requests.stub.ts
  src/frontend/src/utils/pipes.ts
Labels: Reviewed, Reid

#1688 #1448 benjamin zhu add ability to edit vendors
  src/backend/src/controllers/reimbursement-requests.controllers.ts
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/utils/reimbursement-requests.utils.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
Labels: Approved, Ji-min

#1709 #1604 Archivable Teams Edit Schema
  src/backend/src/prisma/migrations/20231129022802_added_archived_user_fields_in_team_and_updated_user/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/tests/test-data/teams.test-data.ts
Labels: Ready for Review, Reid
