Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2023-12, with the labels that each got.

#1699 #1659 visual indication when tabbing through delete and add
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
Labels: Ready for Review, Reid

#1708 #1611 Deny Reimbursement Request Frontent
  src/backend/src/services/reimbursement-requests.services.ts
  src/frontend/src/apis/finance.api.ts
  src/frontend/src/hooks/finance.hooks.ts
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
  src/frontend/src/utils/urls.ts
Labels: Ready for Review, Reid

#1652 #1565 late wp reminder popup
  src/frontend/src/pages/HomePage/Home.tsx
  src/frontend/src/pages/HomePage/OverdueWorkPackageAlerts.tsx
Labels: Ready for Review, Ryan

#1560 #1517 updated teamsRouter to check if user is lead of team before edi…
  src/backend/src/services/teams.services.ts
  src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
Labels: Ready for Review, Sean

#1721 #1640 change request stage gate details page redesign pt2
  src/frontend/src/components/InfoBlock.tsx
  src/frontend/src/layouts/PageTitle/PageTitle.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/ImplementedChangesList.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/ReviewNotes.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/StageGateDetails.tsx
  src/frontend/src/tests/pages/ChangeRequestDetailPage/ImplementedChangesList.test.tsx
  src/frontend/src/tests/pages/ChangeRequestDetailPage/ReviewNotes.test.tsx
Labels: Reviewed, Reid

#1717 #1637: reformatted cards on overiew page
  src/frontend/src/components/ChangeRequestDetailCard.tsx
  src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx
  src/frontend/src/utils/enum-pipes.ts
Labels: Ready for Review, Reid

#1737 #1642 cr popup same wbs
  src/frontend/src/pages/ChangeRequestDetailPage/OtherChangeRequestsPopupTabs.tsx
Labels: Reviewed, Reid

#1743 #1644 proposed solution redesign
  src/frontend/src/components/NERButton.tsx
  src/frontend/src/layouts/PageTitle/PageTitle.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/ProposedSolutionView.tsx
  src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
  src/frontend/src/pages/CreateChangeRequestPage/CreateProposedSolutionsList.tsx
  src/frontend/src/tests/pages/ChangeRequestDetailPage/ProposedSolutionView.test.tsx
  src/frontend/src/tests/pages/ChangeRequestDetailPage/ProposedSolutionsList.test.tsx
  src/frontend/src/tests/pages/CreateChangeRequestPage/CreateProposedSolutionsList.test.tsx
Labels: Reviewed, Sean
