Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2024-02, with the labels that each got.

#2052 #2025 Added my name to credits
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Approved

#2043 #1497-remove-type-any-from-TaskListComponents.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListComponents.tsx
Labels: Approved, Sean

#2031 #1755: Added Reimbursement Disclaimer
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Labels: Reviewed, Sean

#2048 #1999 added testing stage to work package forms
  src/backend/src/prisma/migrations/20240201035326_add_testing_stage_to_work_packages/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/utils/validation.utils.ts
  src/frontend/src/tests/pages/ProjectDetailPage/ProjectViewContainer.test.tsx
  src/frontend/src/utils/enum-pipes.ts
  src/shared/src/types/work-package-types.ts
Labels: back-end, medium, front-end

#2051 #1441 associated CR's not deleted on WP delete
  src/backend/src/services/work-packages.services.ts
Labels: Ready for Review

#1891 #1846 added design review calendar to schema
  src/backend/src/prisma/migrations/20240205053243_/migration.sql
  src/backend/src/prisma/schema.prisma
Labels: Reviewed

#2071 #2070 addd my name to credits
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Approved

#1983 #1982-AlexPark-Credits
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Reviewed, Ryan

#2080 #1788: Disabled New Assembly Btn for Guests
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOMTab.tsx
Labels: Ready for Review, Sean

#2055 #2054: Added my name to the credits page
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Reviewed, Aaryan

#2090 #2029 Added my name to credits
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Ready for Review, Bradford

#2044 #1989 hard deleted delete manufacturer endpoint
  src/backend/src/prisma/migrations/20240208041850_deleted_date_deleted_from_manufacturer/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/manufacturer.transformer.ts
  src/backend/src/transformers/material.transformer.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
  src/shared/src/types/bom-types.ts
Labels: medium, Aaryan

#2045 #1582: added the endpoint and started doing the tests
  src/backend/src/controllers/reimbursement-requests.controllers.ts
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/tests/reimbursement-requests.test.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
Labels: Reviewed, Sean

#2007 #1762-New Button for Action Dropdown
  src/frontend/src/pages/CreateChangeRequestPage/CreateChangeRequestView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
Labels: Reviewed

#2050 #1518 Reply to Slack thread on CR approved/implemented
  src/backend/src/integrations/slack.ts
  src/backend/src/prisma/migrations/20240203205255_add_slack_threads_to_change_request/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/services/change-requests.services.ts
  src/backend/src/utils/change-requests.utils.ts
  src/backend/tests/change-requests.test.ts
Labels: spike, Ready for Review

#2067 #2001 made notes optional
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/migrations/20240205031253_changed_material_notes_to_optional/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/material.transformer.ts
  src/backend/tests/projects.test.ts
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
  src/frontend/src/utils/bom.utils.ts
  src/shared/src/types/bom-types.ts
Labels: Ready for Review, Aaryan

#2089 #1873 added a placeholder value to the account code
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementFormView.tsx
Labels: Aaryan

#2088 #2088-table-highlight
  src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsTable.tsx
Labels: Reviewed

#2091 #2079- added budget/cash refund source column to the request table
  src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
Labels: Reviewed, Bradford

#2038 #1544: added create LinkType frontend tool
  src/backend/src/services/projects.services.ts
  src/backend/tests/projects.test.ts
  src/frontend/src/apis/projects.api.ts
  src/frontend/src/hooks/projects.hooks.ts
  src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx
  src/frontend/src/pages/AdminToolsPage/FinanceConfig/AccountCodeFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/CreateLinkTypeModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeTable.tsx
  src/frontend/src/utils/types.ts
  src/frontend/src/utils/urls.ts
Labels: Reviewed

#2042 #1502: removed any types in auth.utils.ts
  src/backend/src/utils/auth.utils.ts
Labels: Reviewed, Jack

#2065 #1941 send a notif for deny reimbursement
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/utils/slack.utils.ts
  src/backend/tests/reimbursement-requests.test.ts
Labels: Reviewed

#2098 #1794: Allow Guests to browse without SlackId
  src/frontend/src/app/AppAuthenticated.tsx
  src/frontend/src/app/AppPublic.tsx
  src/frontend/src/pages/HomePage/Home.tsx
  src/frontend/src/tests/app/AppAuthenticated.test.tsx
Labels: Ready for Review, Ji-min, Reid

#2097 #1950 made dropdowns for assemblies
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx
  src/frontend/src/utils/bom.utils.ts
Labels: Jack

#2116 Submit to sabo can now be reopenable
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
Labels: Reviewed

#2014 #1928 fix color bom
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx
  src/frontend/src/utils/bom.utils.ts
Labels: Ready for Review

#2151 #1779 jake hensley change request review timeline warning showing up on deny
  src/frontend/src/pages/ChangeRequestDetailPage/ReviewChangeRequestView.tsx
Labels: Reviewed, Reid, Bradford

#2107 #2009 added get user schedule settings endpoint
  src/backend/src/controllers/users.controllers.ts
  src/backend/src/routes/users.routes.ts
  src/backend/src/services/users.services.ts
  src/backend/src/transformers/user-schedule-settings.transformer.ts
  src/backend/tests/test-data/users.test-data.ts
  src/backend/tests/users.test.ts
  src/shared/src/types/user-types.ts
Labels: Sean

#2110 #1486 - Remove 'any' type from LinksEditView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/LinksEditView.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
Labels: Martin

#2047 #1872: Added reimbursed status on frontend
  src/frontend/src/components/ReimbursementRequestStatusPill.tsx
  src/frontend/src/layouts/PageTitle/PageTitle.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
  src/frontend/src/utils/enum-pipes.ts
Labels: Reviewed

#2160 remove any from teams.hooks.ts
  src/frontend/src/hooks/teams.hooks.ts
Labels: Reviewed, Martin

#2021 #1661: added auto-incrementing identifier in RR
  src/backend/src/prisma/migrations/20240129020615_rr_identifier/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/transformers/reimbursement-requests.transformer.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Ready for Review, Sean, Reid

#2125 #1493 refactoring remove any type from srcfrontendsrcpagesfinancepagereimbursementrequestformreimbursementproducttabletsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementProductTable.tsx
Labels: Reviewed, Martin
