Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2024-06, with the labels that each got.

#2617 #2154 created endpoint and hook for delete wp template
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/work-package-templates.routes.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/src/utils/work-packages.utils.ts
  src/backend/tests/test-utils.ts
  src/backend/tests/unmocked/work-package-template.test.ts
  src/frontend/src/apis/work-packages.api.ts
  src/frontend/src/hooks/work-packages.hooks.ts
  src/frontend/src/utils/urls.ts
Labels: Reviewed

#2643 #2630 added distinction between project and work package proposed changes
  src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffPanel.tsx
Labels: Ready for Review

#2645 #2628 Delete Work Package Template Button
  src/frontend/src/hooks/work-packages.hooks.ts
  src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/CreateDescriptionBulletTypeModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/DescriptionBulletTypeTable.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/WorkPackageTemplateTable.tsx
Labels: Approved

#2648 #1587: Copied Changes from old branch to this branch
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/src/services/work-packages.services.ts
Labels: Ready for Review

#2640 #2263 Created setUsefulLinks endpoint
  src/backend/index.ts
  src/backend/src/controllers/organizations.controller.ts
  src/backend/src/prisma/migrations/20240601212512_add_useful_links_to_organization/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/organizations.routes.ts
  src/backend/src/services/organizations.service.ts
  src/backend/src/utils/organizations.utils.ts
  src/backend/tests/test-data/organizations.test-data.ts
  src/backend/tests/test-utils.ts
  src/backend/tests/unmocked/organization.test.ts
Labels: Reviewed

#2629 #2496 change delete work package view to ner form modal
  src/frontend/src/pages/WorkPackageDetailPage/DeleteWorkPackageModalContainer/DeleteWorkPackageView.tsx
Labels: Reviewed

#2607 2159 work package templates hook up to createedit wp pages
  src/backend/src/prisma/seed.ts
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageTemplateSection.tsx
Labels: front-end, difficult, Reviewed

#2675 #2635 added useful links to homepage
  src/backend/src/prisma/seed.ts
  src/frontend/src/pages/HomePage/UsefulLinks.tsx
Labels: Ready for Review
