Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2024-04, with the labels that each got.

#2179 #1683 Capitalized SABO under the RR status names in the Finance page
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/ReimbursementRequestDetailsView.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
Labels: Ready for Review, Ji-min, Reid

#2174 #1893 Schema Changes for Auto-Implementing CRs
  src/backend/src/prisma/migrations/20240401033435_added_wbs_project_workpackage_proposed_changes/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/tests/test-data/change-requests.test-data.ts
Labels: Reviewed, Reid

#2301 #1789 - Disabled 'Actions' button for guest roles.
  src/frontend/src/components/ActionsMenu.tsx
Labels: Ready for Review

#2297 #2076: made seed data for slackbot testing
  src/backend/src/prisma/seed-data/teams.seed.ts
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Ready for Review, Reviewed, Sean

#2303 #1247 all work package edits are now marked as active
  src/backend/src/services/work-packages.services.ts
Labels: Jack

#2329 #1894: draft of update create scope cr endpoint
  src/backend/src/controllers/change-requests.controllers.ts
  src/backend/src/prisma-query-args/change-requests.query-args.ts
  src/backend/src/prisma-query-args/scope-change-requests.query-args.ts
  src/backend/src/prisma/migrations/20240411234240_auto_implementing_crs/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/change-requests.routes.ts
  src/backend/src/services/change-requests.services.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/src/transformers/change-requests.transformer.ts
  src/backend/src/utils/change-requests.utils.ts
  src/backend/src/utils/projects.utils.ts
  src/backend/src/utils/validation.utils.ts
  src/backend/tests/test-data/change-requests.test-data.ts
  src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
  src/shared/src/types/change-request-types.ts
  src/shared/src/types/project-types.ts
Labels: Ready for Review, Sean, Ji-min, Reid

#2123 #1939-ReimbursementRequestTableSort
  src/frontend/src/pages/FinancePage/FinanceComponents/ColumnHeader.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestsSection.tsx
  src/frontend/src/utils/reimbursement-request.utils.ts
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Ready for Review, Ji-min, Reid

#2346 2326 drc debugs set team teamtype endpoint
  src/backend/src/controllers/teams.controllers.ts
  src/backend/src/prisma-query-args/teams.query-args.ts
  src/backend/src/prisma/migrations/20240411015314_added_team_type_to_team/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/teams.routes.ts
  src/backend/src/services/teams.services.ts
  src/backend/src/transformers/teams.transformer.ts
  src/backend/tests/mocked/teams.test.ts
  src/backend/tests/test-data/teams.test-data.ts
  src/shared/src/types/team-types.ts
Labels: back-end

#2335 #1932: Delete Vendor Endpoint
  src/backend/src/controllers/reimbursement-requests.controllers.ts
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/tests/mocked/reimbursement-requests.test.ts
Labels: Reviewed

#2254 #2102: Add Ready to Order status
  src/backend/src/prisma/migrations/20240325194935_add_ready_to_order_status/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/utils/validation.utils.ts
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableCustomCells.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
  src/shared/src/types/bom-types.ts
Labels: back-end, Jack

#2143 #2104 delete manufac
  src/backend/src/prisma/migrations/20240404004905_add_date_deleted_manufacturer/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/services/projects.services.ts
  src/backend/src/transformers/manufacturer.transformer.ts
  src/backend/src/transformers/material.transformer.ts
  src/backend/tests/mocked/projects.test.ts
  src/backend/tests/test-data/projects.test-data.ts
  src/frontend/src/apis/bom.api.ts
  src/frontend/src/hooks/bom.hooks.ts
  src/frontend/src/pages/AdminToolsPage/BOMConfig/ManufacturerDeleteModal.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/ManufacturerTable.tsx
  src/frontend/src/utils/urls.ts
  src/shared/src/types/bom-types.ts
Labels: Reviewed

#2255 #1545: edit linktypes
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/frontend/src/apis/projects.api.ts
  src/frontend/src/components/ReactHookTextField.tsx
  src/frontend/src/hooks/projects.hooks.ts
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/CreateLinkTypeModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/EditLinkTypeModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/LinkTypeTable.tsx
  src/frontend/src/utils/urls.ts
Labels: Jack

#2308 #2122: Added ability to delete assemblies
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/tests/mocked/projects.test.ts
  src/frontend/src/apis/bom.api.ts
  src/frontend/src/hooks/bom.hooks.ts
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTable.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableWrapper.tsx
  src/frontend/src/utils/urls.ts
Labels: Reviewed

#2282 #2150 edit work package template endpoint
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/src/transformers/work-package-template.transformer.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/src/utils/validation.utils.ts
  src/shared/src/types/work-package-types.ts
Labels: back-end, difficult

#2194 #1600: Added Working Preview to Create Team Description
  src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
Labels: Reviewed, Jack

#2180 #1766 upgrade member to lead
  src/backend/src/services/teams.services.ts
  src/backend/src/utils/teams.utils.ts
  src/backend/tests/mocked/teams.test.ts
  src/frontend/src/pages/TeamsPage/TeamMembersPageBlock.tsx
Labels: Jack

#2317 2103 Moved the tooltip from the left side to the right side
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
Labels: Reviewed
