Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2024-03, with the labels that each got.

#2177 #2173 slack noti when invited to a design review
  src/backend/src/services/change-requests.services.ts
  src/backend/src/utils/change-requests.utils.ts
  src/backend/src/utils/slack.utils.ts
  src/backend/tests/change-requests.test.ts
Labels: back-end, straightforward

#2175 #2061 get all design reviews endpoint
  src/backend/src/controllers/design-review.controllers.ts
  src/backend/src/routes/design-review.routes.ts
  src/backend/src/services/design-review.services.ts
  src/backend/tests/design-reviews.test.ts
Labels: Ready for Review, Sean

#2126 #2083 add finance team to seed data
  src/backend/src/prisma/seed-data/teams.seed.ts
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: back-end, Reviewed, Sean

#2170 #2081 Receipt Upload not Required in RR form locally
  src/frontend/src/pages/FinancePage/ReimbursementRequestForm/ReimbursementRequestForm.tsx
Labels: Ready for Review

#2184 #2128 admin tools tabs
  src/frontend/src/pages/AdminToolsPage/AdminToolsPage.tsx
Labels: Reid

#2053 #690 Removed any types from work-packages.hooks.tsx
  src/frontend/src/apis/work-packages.api.ts
  src/frontend/src/hooks/work-packages.hooks.ts
  src/frontend/src/pages/WorkPackageForm/WorkPackageForm.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
Labels: Reviewed, Jack

#2171 #795 slack ping on task deadline
  .github/workflows/task-deadline-notifications.yml
  src/backend/index.ts
  src/backend/src/controllers/notifications.controllers.ts
  src/backend/src/routes/notifications.routes.ts
  src/backend/src/services/notifications.services.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/services/tasks.services.ts
  src/backend/src/utils/auth.utils.ts
  src/backend/src/utils/notifications.utils.ts
  src/backend/src/utils/teams.utils.ts
Labels: Ready for Review

#2092 #2082 add ability to generate cash vs budget receipts
  src/frontend/src/hooks/finance.hooks.ts
  src/frontend/src/pages/FinancePage/FinanceComponents/GenerateReceiptsModal.tsx
  src/frontend/src/pages/FinancePage/FinancePage.tsx
Labels: front-end, difficult, Reviewed

#2189 #1312 scrollbar cutting off wp cards homescreen
  src/frontend/src/pages/HomePage/UpcomingDeadlines.tsx
Labels: Ready for Review, Reid

#2188 #2129 add drc page
  src/frontend/src/app/AppAuthenticated.tsx
  src/frontend/src/layouts/PageTitle/PageTitle.tsx
  src/frontend/src/layouts/Sidebar/Sidebar.tsx
  src/frontend/src/pages/Calendar/Calendar.tsx
  src/frontend/src/pages/Calendar/CalendarComponents/CalendarDayCard.tsx
  src/frontend/src/pages/Calendar/CalendarComponents/FillerCalendarDayCard.tsx
  src/frontend/src/pages/Calendar/CalendarComponents/MonthSelector.tsx
  src/frontend/src/pages/Calendar/CalendarPage.tsx
  src/frontend/src/utils/design-review.utils.tsx
  src/frontend/src/utils/pipes.ts
  src/frontend/src/utils/routes.ts
Labels: front-end, new feature, Jack

#2198 #2121 moving create unit functionality to admin tools
  src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/CreateUnitFormModal.tsx
  src/frontend/src/pages/AdminToolsPage/BOMConfig/UnitTable.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
Labels: Approved

#2024 #2004 - Make BOM manufacturer select an autocomplete
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
Labels: Reviewed, Martin

#2169 DRAFT PR #2133 created modal view
  src/frontend/src/app/AppAuthenticated.tsx
  src/frontend/src/components/NERModal.tsx
  src/frontend/src/pages/CalendarPage/Calendar.tsx
  src/frontend/src/pages/CalendarPage/CalendarComponents/CalendarDayCard.tsx
  src/frontend/src/pages/CalendarPage/CalendarComponents/FillerCalendarDayCard.tsx
  src/frontend/src/pages/CalendarPage/CalendarComponents/MonthSelector.tsx
  src/frontend/src/pages/CalendarPage/CalendarPage.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/AvailabilityScheduleView.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/AvailabilityView.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/DesignReviewDetailPage.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/UserAvailabilitesView.tsx
  src/frontend/src/pages/CalendarPage/SchedulingComponents/AvailabilityEditModal.tsx
  src/frontend/src/pages/CalendarPage/SchedulingComponents/EditAvailability.tsx
  src/frontend/src/pages/CalendarPage/SchedulingComponents/TimeSlot.tsx
  src/frontend/src/utils/design-review.utils.ts
  src/frontend/src/utils/design-review.utils.tsx
  src/frontend/src/utils/routes.ts
Labels: front-end, new feature, Aaryan

#2190 #1986-Edit-Design-Review-Endpoint(fixed)
  src/backend/index.ts
  src/backend/src/controllers/design-reviews.controllers.ts
  src/backend/src/prisma-query-args/design-reviews.query-args.ts
  src/backend/src/routes/design-review.routes.ts
  src/backend/src/routes/design-reviews.routes.ts
  src/backend/src/services/design-reviews.services.ts
  src/backend/src/transformers/design-reviews.transformer.ts
  src/backend/src/utils/design-reviews.utils.ts
  src/backend/src/utils/users.utils.ts
  src/backend/src/utils/validation.utils.ts
  src/backend/tests/design-reviews.test.ts
  src/backend/tests/test-data/design-reviews.test-data.ts
Labels: Ready for Review, Jack

#2186 1998 User Schedule Set Endpoint
  src/backend/src/controllers/users.controllers.ts
  src/backend/src/routes/users.routes.ts
  src/backend/src/services/users.services.ts
  src/backend/tests/users.test.ts
Labels: Reviewed, Jack

#2216 #2132: Schedule Settings Section
  src/backend/src/services/users.services.ts
  src/backend/tests/users.test.ts
  src/frontend/src/apis/users.api.ts
  src/frontend/src/components/TimeSlot.tsx
  src/frontend/src/hooks/users.hooks.ts
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/AvailabilityScheduleView.tsx
  src/frontend/src/pages/CalendarPage/SchedulingComponents/AvailabilityEditModal.tsx
  src/frontend/src/pages/SettingsPage/Settings.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/Availability/AvailabilityEditModal.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/Availability/EditAvailability.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/Availability/SingleAvailabilityModal.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/Availability/SingleAvailabilityView.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettings.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettingsEdit.tsx
  src/frontend/src/pages/SettingsPage/UserScheduleSettings/UserScheduleSettingsView.tsx
  src/frontend/src/utils/urls.ts
Labels: Ready for Review, Sean, Ji-min, Reid

#2130 #1487: replaced usage of type any with specific types
  src/frontend/src/hooks/change-requests.hooks.ts
  src/frontend/src/pages/WorkPackageDetailPage/ActivateWorkPackageModalContainer/ActivateWorkPackageModalContainer.tsx
Labels: Reviewed, Sean

#2218 #2107 edit dr hook
  src/backend/src/controllers/design-reviews.controllers.ts
  src/frontend/src/apis/design-reviews.api.ts
  src/frontend/src/hooks/design-reviews.hooks.ts
  src/frontend/src/pages/CalendarPage/CalendarPage.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewSummaryModal.tsx
  src/frontend/src/pages/CalendarPage/SummaryComponents/DesignReviewSummaryModalAttendees.tsx
  src/frontend/src/pages/CalendarPage/SummaryComponents/DesignReviewSummaryModalButtons.tsx
  src/frontend/src/pages/CalendarPage/SummaryComponents/DesignReviewSummaryModalDetails.tsx
  src/frontend/src/utils/urls.ts
Labels: new feature, Jack

#2226 #2028 use delete design review hook
  src/frontend/src/apis/design-reviews.api.ts
  src/frontend/src/hooks/design-reviews.hooks.ts
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/DesignReviewDetailPage.tsx
  src/frontend/src/utils/urls.ts
Labels: Ready for Review, Reid

#2215 #2136 finalize design review modal
  src/backend/src/controllers/design-reviews.controllers.ts
  src/backend/src/prisma-query-args/design-reviews.query-args.ts
  src/backend/src/services/users.services.ts
  src/backend/src/transformers/design-reviews.transformer.ts
  src/backend/src/transformers/designReviewUser.transformer.ts
  src/backend/tests/test-data/design-reviews.test-data.ts
  src/backend/tests/users.test.ts
  src/frontend/src/apis/users.api.ts
  src/frontend/src/components/TimeSlot.tsx
  src/frontend/src/hooks/design-reviews.hooks.ts
  src/frontend/src/hooks/users.hooks.ts
  src/frontend/src/pages/CalendarPage/DesignReviewCreateModal.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/AvailabilityScheduleView.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/AvailabilityView.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/DesignReviewDetailPage.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/FinalizeDesignReviewDetailsModal.tsx
  src/frontend/src/pages/CalendarPage/DesignReviewDetailPage/UserAvailabilitesView.tsx
  src/frontend/src/utils/design-review.utils.ts
  src/frontend/src/utils/pipes.ts
  src/shared/src/types/design-review-types.ts
  src/shared/src/types/user-types.ts
Labels: front-end, difficult

#2245 #2243 changed headings in Admin Page to NER Red
  src/frontend/src/pages/AdminToolsPage/AdminToolsAttendeeDesignReviewInfo.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsBOMConfig.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsFinanceConfig.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsSlackUpcomingDeadlines.tsx
  src/frontend/src/pages/AdminToolsPage/AdminToolsUserManagement.tsx
  src/frontend/src/pages/AdminToolsPage/TeamsTools.tsx
Labels: front-end, straightforward

#2176 #2113: set defaultValue for requestReviewDropdown to already request…
  src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestActionMenu.tsx
Labels: Approved, Reviewed, Martin

#2115 added error in start date field
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormDetails.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
Labels: good first issue, front-end, straightforward, stale, Jack

#2167 #2119-BOM-price-label-change
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/BOMTableWrapper.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
  src/frontend/src/utils/bom.utils.ts
Labels: Reviewed

#2196 #issue-2003 added info icon to the manufacturer field
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/BOM/MaterialForm/MaterialFormView.tsx
Labels: Reviewed

#2258 #2257 removed set date from design review succeeds test
  src/backend/tests/design-reviews.test.ts
Labels: Jack

#2182 #1764: added auto complete for change request ID in edit work package
  src/frontend/src/components/ChangeRequestDropdown.tsx
Labels: Ready for Review, Ji-min, Reid

#2246 #2155 get single work package template endpoint
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/prisma-query-args/work-package-template.query-args.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/users.services.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/src/transformers/change-requests.transformer.ts
  src/backend/src/transformers/design-reviews.transformer.ts
  src/backend/src/transformers/designReviewUser.transformer.ts
  src/backend/src/transformers/projects.transformer.ts
  src/backend/src/transformers/proposed-solutions.transformer.ts
  src/backend/src/transformers/reimbursement-requests.transformer.ts
  src/backend/src/transformers/tasks.transformer.ts
  src/backend/src/transformers/teams.transformer.ts
  src/backend/src/transformers/user.transformer.ts
  src/backend/src/transformers/work-package-template.transformer.ts
  src/backend/src/transformers/work-packages.transformer.ts
  src/backend/tests/mocked/users.test.ts
  src/backend/tests/test-data/reimbursement-requests.test-data.ts
  src/backend/tests/test-data/tasks.test-data.ts
  src/shared/src/types/work-package-types.ts
Labels: back-end, difficult

#2168 #2106: added related change request tab
  src/frontend/src/components/ChangeRequestRow.tsx
  src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ChangeRequestTab.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectViewContainer.tsx
Labels: Reviewed, Reid, Bradford

#2289 #1369 remove horizontal scroll bar
  src/frontend/src/app/AppAuthenticated.tsx
  src/frontend/src/layouts/Sidebar/Sidebar.tsx
  src/frontend/src/tests/layouts/Sidebar/Sidebar.test.tsx
Labels: Jack
