Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2024-05, with the labels that each got.

#2310 #2156 added endpoint for getting all work package templates. edited w…
  src/backend/src/controllers/work-packages.controllers.ts
  src/backend/src/routes/work-packages.routes.ts
  src/backend/src/services/work-packages.services.ts
Labels: Reviewed

#2075 #1254 renamed lead and manager in wbs in prisma schema
  src/backend/src/prisma-query-args/projects.query-args.ts
  src/backend/src/prisma-query-args/work-packages.query-args.ts
  src/backend/src/prisma/manual.ts
  src/backend/src/prisma/migrations/20240207185652_renamed_lead_manager_wbselement/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/prisma/seed.ts
  src/backend/src/services/change-requests.services.ts
  src/backend/src/services/tasks.services.ts
  src/backend/src/services/work-packages.services.ts
  src/backend/src/transformers/projects.transformer.ts
  src/backend/src/transformers/work-packages.transformer.ts
  src/backend/src/utils/description-bullets.utils.ts
  src/backend/src/utils/projects.utils.ts
  src/backend/src/utils/slack.utils.ts
  src/backend/src/utils/tasks.utils.ts
  src/backend/tests/test-data/projects.test-data.ts
  src/backend/tests/test-data/wbs-element.test-data.ts
  src/backend/tests/test-data/work-packages.test-data.ts
  src/frontend/src/components/ProjectDetailCard.tsx
  src/frontend/src/pages/ChangeRequestsPage/ChangeRequestsOverview.tsx
  src/frontend/src/pages/HomePage/OverdueWorkPackageAlerts.tsx
  src/frontend/src/pages/HomePage/WorkPackageCard.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/ProjectDetails.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskList.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectViewContainer/TaskList/TaskListTabPanel.tsx
  src/frontend/src/pages/ProjectsPage/ProjectsOverview.tsx
  src/frontend/src/pages/ProjectsPage/ProjectsTable.tsx
  src/frontend/src/pages/TeamsPage/ProjectCardsView.tsx
  src/frontend/src/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
  src/frontend/src/tests/pages/HomePage/UpcomingDeadlines.test.tsx
  src/frontend/src/tests/pages/HomePage/WorkPackagesByTimelineStatus.test.tsx
  src/frontend/src/tests/pages/WorkPackageDetailPage/WorkPackageViewContainer/WorkPackageDetails.test.tsx
  src/frontend/src/tests/test-support/test-data/projects.stub.ts
  src/frontend/src/tests/test-support/test-data/work-packages.stub.ts
  src/shared/src/types/project-types.ts
Labels: Reviewed

#2359 #1903 create project button
  src/backend/src/prisma/migrations/20240425220706_remove_new_project_and_add_car_number/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/services/change-requests.services.ts
  src/backend/src/transformers/change-requests.transformer.ts
  src/backend/src/utils/validation.utils.ts
  src/frontend/src/components/TeamsDropdown.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectCreateContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectForm.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectFormDetails.tsx
  src/frontend/src/pages/ProjectsPage/ProjectsPage.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
  src/shared/src/types/change-request-types.ts
  src/shared/src/types/project-types.ts
Labels: Jack

#2375 #2365 Added Filtering and Searching to the Gantt Chart Page
  src/backend/src/prisma-query-args/projects.query-args.ts
  src/backend/src/prisma/seed-data/teams.seed.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/transformers/projects.transformer.ts
  src/frontend/src/components/SearchBar.tsx
  src/frontend/src/pages/GanttPage/GanttChart.tsx
  src/frontend/src/pages/GanttPage/GanttChartComponents/GanttChartFilters.tsx
  src/frontend/src/pages/GanttPage/GanttChartComponents/GanttChartFiltersButton.tsx
  src/frontend/src/pages/GanttPage/GanttChartPage.tsx
  src/frontend/src/pages/GanttPage/GanttChartSection.tsx
  src/frontend/src/utils/gantt.utils.ts
  src/shared/src/types/team-types.ts
Labels: Ready for Review, Reid

#2144 Remove any type from src/frontend/src/hooks/description-bullets.hooks.ts
  src/frontend/src/hooks/description-bullets.hooks.ts
  src/frontend/src/tests/test-support/mock-hooks.ts
Labels: Reviewed

#2163 #1531: added 8 members and made a ravens team
  src/backend/src/prisma/seed-data/users.seed.ts
  src/backend/src/prisma/seed.ts
Labels: Reviewed

#2337 #2261 edit work package template hook
  src/frontend/src/apis/work-packages.api.ts
  src/frontend/src/hooks/work-packages.hooks.ts
  src/frontend/src/utils/urls.ts
Labels: medium, front-end

#2380 #2327 frontend for set team type modal and hook
  src/frontend/src/apis/team-types.api.ts
  src/frontend/src/hooks/team-types.hooks.ts
  src/frontend/src/hooks/teams.hooks.ts
  src/frontend/src/pages/TeamsPage/SetTeamTypeModal.tsx
  src/frontend/src/pages/TeamsPage/TeamSpecificPage.tsx
  src/frontend/src/utils/urls.ts
Labels: back-end, front-end, difficult

#2343 #2290: add edit assembly endpoint
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/projects.services.ts
  src/backend/tests/test-data/projects.test-data.ts
Labels: Reviewed

#2363 #1944-CaioDaSilva-SortTable
  src/frontend/src/pages/FinancePage/RefundsSection.tsx
Labels: Reviewed, Jack

#2333 #2277: Display Difference Page
  src/backend/src/transformers/change-requests.transformer.ts
  src/backend/src/utils/validation.utils.ts
  src/frontend/src/apis/transformers/change-requests.transformers.ts
  src/frontend/src/pages/ChangeRequestDetailPage/ChangeRequestDetailsView.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffPanel.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffSection.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffSectionCreate.tsx
  src/frontend/src/pages/ChangeRequestDetailPage/DiffSection/DiffSectionEdit.tsx
  src/frontend/src/pages/ProjectDetailPage/ProjectForm/ProjectEditContainer.tsx
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
  src/frontend/src/utils/change-request.utils.ts
  src/frontend/src/utils/diff-page.utils.ts
  src/frontend/src/utils/pipes.ts
  src/shared/src/types/project-types.ts
Labels: Ready for Review, Reid

#2383 #2382 Gantt Chart Editing Functionality
  src/frontend/src/components/NERModal.tsx
  src/frontend/src/pages/GanttPage/GanttChart.tsx
  src/frontend/src/pages/GanttPage/GanttChartComponents/GanttRequestChangeModal.tsx
  src/frontend/src/pages/GanttPage/GanttChartComponents/GanttTaskBar.tsx
  src/frontend/src/pages/GanttPage/GanttChartPage.tsx
  src/frontend/src/pages/GanttPage/GanttChartSection.tsx
  src/frontend/src/utils/gantt.utils.ts
Labels: front-end, difficult

#2610 #2399: changed the color of the cancel button on the create work pack…
  src/frontend/src/pages/WorkPackageForm/WorkPackageFormView.tsx
Labels: Ready for Review

#2615 #2262 created use single work package template hook
  src/frontend/src/apis/work-packages.api.ts
  src/frontend/src/hooks/work-packages.hooks.ts
Labels: Approved

#2602 2325 drc debugs infer team type from work package
  src/backend/src/prisma-query-args/work-packages.query-args.ts
  src/backend/src/transformers/projects.transformer.ts
  src/backend/src/transformers/work-packages.transformer.ts
  src/frontend/src/pages/CalendarPage/DesignReviewCreateModal.tsx
  src/frontend/src/tests/test-support/test-data/work-packages.stub.ts
  src/shared/src/types/project-types.ts
Labels: Reviewed
