Repository Northeastern-Electric-Racing/FinishLine, pull requests merged in 2025-03, with the labels that each got.

#3222 #3151: update getAllVendors endpoint
  src/backend/src/prisma-query-args/reimbursement-requests.query-args.ts
  src/backend/src/prisma-query-args/vendor.query-args.ts
  src/backend/src/prisma/migrations/20250127014440_finance_redesign/migration.sql
  src/backend/src/prisma/schema.prisma
  src/backend/src/routes/reimbursement-requests.routes.ts
  src/backend/src/services/reimbursement-requests.services.ts
  src/backend/src/transformers/reimbursement-requests.transformer.ts
  src/backend/tests/unit/reimbursement-requests.test.ts
  src/backend/tests/unmocked/reimbursement-requests.test.ts
  src/frontend/src/apis/transformers/reimbursement-requests.transformer.ts
  src/frontend/src/pages/FinancePage/FinanceComponents/GenerateReceiptsModal.tsx
  src/frontend/src/pages/FinancePage/ReimbursementRequestDetailPage/SubmitToSaboModal.tsx
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Ready for Review, Sean

#3257 #3192- finance redesign deleteSponsor endpoint
  src/backend/index.ts
  src/backend/src/controllers/finance.controllers.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/finance.routes.ts
  src/backend/src/services/finance.services.ts
  src/backend/src/utils/errors.utils.ts
  src/backend/tests/unit/finance.test.ts
Labels: Ready for Review, Sean

#3280 #3279 get all sponsors endpoint
  src/backend/src/controllers/finance.controllers.ts
  src/backend/src/prisma-query-args/sponsor.query.args.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/finance.routes.ts
  src/backend/src/services/finance.services.ts
  src/backend/src/transformers/finance.transformer.ts
  src/backend/tests/unit/finance.test.ts
  src/shared/index.ts
  src/shared/src/types/finance-types.ts
Labels: Ready for Review, Sean

#3310 #3292 added my name to the credits page
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Ready for Review, Sean

#3272 #3152 Updating Material Transformer/Endpoints
  src/backend/src/controllers/projects.controllers.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/projects.routes.ts
  src/backend/src/services/boms.services.ts
  src/backend/src/transformers/material.transformer.ts
  src/backend/src/transformers/reimbursement-requests.transformer.ts
  src/backend/tests/unmocked/project.test.ts
  src/frontend/src/apis/transformers/bom.transformers.ts
  src/shared/src/types/bom-types.ts
  src/shared/src/types/reimbursement-requests-types.ts
Labels: Ready for Review, Sean

#3269 #3194 getSponsorTasks endpoint
  src/backend/src/controllers/finance.controllers.ts
  src/backend/src/routes/finance.routes.ts
  src/backend/src/services/finance.services.ts
  src/backend/src/transformers/sponsor-task.transformer.ts
  src/backend/tests/test-utils.ts
  src/backend/tests/unit/finance.test.ts
  src/shared/index.ts
Labels: Ready for Review, Sean

#3347 #3345 Added my name to credits page
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: credits

#3242 #3199 project name abbreviations table
  src/frontend/src/pages/AdminToolsPage/AdminToolsProjectsConfig.tsx
  src/frontend/src/pages/AdminToolsPage/ProjectsConfig/AbbreviationsTable.tsx
Labels: Ready for Review, cad review

#3344 #3296 create sponsor task endpoint
  src/backend/src/controllers/finance.controllers.ts
  src/backend/src/prisma/seed.ts
  src/backend/src/routes/finance.routes.ts
  src/backend/src/services/finance.services.ts
  src/backend/tests/unit/finance.test.ts
Labels: Ready for Review, Sean

#3362 #3350: Added name to credits page
  src/frontend/src/pages/CreditsPage/CreditsPage.tsx
Labels: Ready for Review, Sean
